project:
  type: book
  output-dir: _output

book:
  title: "ITD"
  subtitle: "XXXXXx"
  author: "NetLab/UFRJ"
  date: today
  chapters:
    - index.qmd
    - introduction.qmd
    - methodology.qmd
    - part: "Brazil"
      chapters:
        - reports/reddit_br.qmd
  # page-footer:
  #   center: "© 2025 Social Media Evaluation Project"

bibliography:
  - bib/references_global.bib
  - bib/reddit.bib

format:
  html:
    theme:
      - _brand.yml
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    embed-resources: false
  pdf:
    documentclass: report
    toc: true
    number-sections: true
    colorlinks: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

# Jupyter kernel for Python code execution
jupyter: python3
