project:
  type: book
  output-dir: _output

book:
  title: "Data Transparency Index"
  #subtitle: "XX"
  author: "NetLab/UFRJ"
  date: today
  repo-url: https://github.com/NetLab-ECO-UFRJ/transparency-index
  repo-actions: [issue]
  chapters:
    - index.qmd
    - introduction.qmd
    - background.qmd
    - recommendations.qmd
    - methodology.qmd
    - part: "Global Assessments"
      chapters:
        - data/2025/global/telegram/telegram.qmd
        - data/2025/global/bluesky/bluesky.qmd
        - data/2025/global/discord/discord.qmd
        - data/2025/global/kwai/kwai.qmd
    - part: "Brazil"
      chapters:
        - data/2025/regional/BR/linkedin/linkedin.qmd
        - data/2025/regional/BR/pinterest/pinterest.qmd
        - data/2025/regional/BR/snapchat/snapchat.qmd
        - data/2025/regional/BR/tiktok/tiktok.qmd
        - data/2025/regional/BR/x/x.qmd
    # - part: "European Union"
    #   chapters: []
    # - part: "United Kingdom"
    #   chapters: []
  # page-footer:
  #   center: "© 2025 Social Media Evaluation Project"

bibliography:
  - bib/references_global.bib
  - bib/reddit.bib

format:
  html:
    theme:
    - cosmo
      # - _brand.yml
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    code-copy: false
    embed-resources: false
  pdf:
    documentclass: report
    toc: true
    number-sections: true
    colorlinks: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

# Jupyter kernel for Python code execution
jupyter: python3
