services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: quarto-site
    labels:
      - "traefik.http.services.web.loadbalancer.server.port=80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "--http-user=admin", "--http-password=laguinho", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
