---
title: "About this Report"
subtitle: "Social Media Data Transparency for Information Integrity"
---

This report is the result of a collaboration between NetLab UFRJ, a research laboratory within the Federal University of Rio de Janeiro (Brazil), and the Minderoo Centre for Technology and Democracy at the University of Cambridge (United Kingdom).

Founded in 2013, NetLab UFRJ is one of Brazil’s leading internet research laboratories. It is dedicated to investigating and diagnosing the phenomenon of digital disinformation and its consequences in the country, with a focus on producing empirical evidence to generate social impact and inform public debate. Learn more on NetLab UFRJ’s [official website](https://www.netlab.eco.br).

The Minderoo Centre for Technology and Democracy is an independent team of researchers based at the University of Cambridge who are rethinking the power relationships between digital technologies, society, and the planet, with the aim of informing policy and shaping public decision-making. Learn more on the Minderoo Centre for Technology and Democracy’s [official website](https://www.minderoo.org/technology-and-democracy).


## How to Cite

If you use this report in your research or work, please cite as:

Santini, R. M., Leal, H., Salles, D., Belisário, A., Mattos, B., & Pinho, D. (2026). *Data Not Found: Social Media Data Transparency for Information Integrity*. NetLab UFRJ & Minderoo Centre for Technology and Democracy.

```bibtex
@techreport{santini2026datanotfound,
  title        = {Data Not Found: Social Media Data Transparency for Information Integrity},
  author       = {Santini, Rose Marie and Leal, Humberto and Salles, Diogo and Bel{\'i}sario, Adriano and Mattos, Bruno and Pinho, Diego},
  year         = {2026},
  institution  = {NetLab UFRJ \& Minderoo Centre for Technology and Democracy},
}
```